### ISSUE TITLE
Vertex Base 0 error when exporting with imported model on latest version of 1.4

### ISSUE THREAD

**Issue by UberGrainy** [TheCrazyT/BlenderMhwModelImporter#6]
Agnaraptor got this error:
https://cdn.discordapp.com/attachments/426494287086092298/525706320716890113/Screenshot_133.png

I got the same error when I updated and tried to export with an imported mesh (the same file previously worked on earlier versions). When I switched back to older versions I was able to export without problem.

**Comment by TheCrazyT** [comment]
Do you have any example file?
I thought that it should never get to that exception line on normal/non-corrupted files.
Guess i was wrong.

**Comment by TheCrazyT** [comment]
I think i fixed it (and also fixed the typo).

**Comment by UberGrainy** [comment]
It seems to export without error now, thanks. Haven't tried the export in-game yet though.
